name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_icolors:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ cbaa19f7-4b2c-4f4c-a5a9-830ea1b11b5f }}
        APP_NAME: ${{ 'tl-shopping-app' }}
      run: |
        cd ./iceStorm/$APP_NAME
        docker login --username=icestorm3675 --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME